[package]
name = "keyboard-layout-analyzer"
version = "0.1.0"
authors = ["s1n7ax <srineshnisala@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
